#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# rbenv
eval "$(rbenv init -)"

# Custom aliases
alias a='alias'

## Docker
a dps='docker ps'
a dpsa='dps -a'
a di='docker images'
a dia='docker images -a'

a dcb='docker-compose build --force-rm'
a dcu='docker-compose up --remove-orphans'
a dcud='docker-compose up --remove-orphans -d'
a dcs='docker-compose stop'
a dcbu='dcb && dcu'
a dcsbu='dcs && dcbu' # harder
a dcl='docker-compose logs -f'
a dcudl='dcud && dcl'

# Git
a git-remove-untracked='git fetch --prune && git branch -r | awk "{print \$1}" | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk "{print \$1}" | xargs git branch -d'
# export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"

# Elixir iex history
export ERL_AFLAGS="-kernel shell_history enabled"

# Elixir version manager
. ${HOME}/.asdf/asdf.sh
. ${HOME}/.asdf/completions/asdf.bash

# Set Spaceship ZSH as a prompt
#autoload -U promptinit; promptinit
#prompt spaceship

# tmux highlighting
export TERM=xterm-256color

# Postgres
export PATH="/usr/local/opt/postgresql@9.5/bin:$PATH"
